### ISSUE TITLE
slash at the end of address makes subpage unavailable

### ISSUE THREAD

**Issue by PawelPodkalicki** [adshares/ads-operator-panel#113]
**Describe the bug**

Adding slash at the end of blockexplorer address makes it impossible to open subpage.

**To Reproduce**

1. Go to https://operator.adshares.net/blockexplorer/
2. Click on any node from Nodes list.
3. Error: page opens with message `This is NotFoundPage component!`

**Expected behavior**

After click on node it's data should be presented.

**Environment (please complete the following information):**

 - OS name and version: Windows 10
 - Browser name and version: Firefox / Chrome

**Additional context**

The source of the error is the slash at the end of address.

**Comment by c3zi** [comment]
Thanks! We'are on it.
